sass:
    sass_dir: assets/_sass
    style: compressed

title: "Fall 2018 CU Blockchain Summit"
tagline: "Workshops | Panels | Networking | 24-hour Hackathon"
about: " The Fall 2018 CU Blockchain Summit is the second student summit
 and hackathon for Colorado students interested in blockchain technology. 
 The summit will feature weekly workshops and panels with blockchain experts, 
 networking with blockchain companies, and a month-long hackathon competition. 
 It all starts on October 13th at the University Memorial Center on the CU Boulder campus, 
 and ends on November 10th at Idea Forge. "
email: blockchain@colorado.edu
register-url: "https://my.cublockchain.org"