sass:
    sass_dir: assets/_sass
    style: compressed

title: "Fall 2018 CU Blockchain Summit"
tagline: "Workshops | Panels | Networking | 24-hour Hackathon"
about: " The Fall 2018 CU Blockchain Summit is the second summit hosted by CU Blockchain
for Colorado students and professionals interested in blockchain technology. 
The summit will feature panels with industry experts, networking with blockchain companies, 
and kick off a 3 week long blockchain project competition. It will take place October 13th at the University Memorial Center 
on the CU Boulder campus, and the project competition concludes on November 3rd at the Idea Forge."
email: blockchain@colorado.edu
register-url: "https://my.cublockchain.org"
